#
# Labtainer Dockerfile
#

ARG registry
FROM $registry/labtainer.network

ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG password
ARG apt_source
ARG version
LABEL version=$version
ENV APT_SOURCE $apt_source
RUN /usr/bin/apt-source.sh

#
#  put package installation here
#

RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

RUN pip3 install paramiko
RUN pip3 install termcolor 

#
# Install the system files found in the _system directory
#

ADD $labdir/$imagedir/sys_tar/sys.tar /
ADD $labdir/sys_$lab.tar.gz /


RUN useradd -ms /bin/bash $user_name
RUN echo "$user_name:$password" | chpasswd
RUN adduser $user_name sudo

#
#  **** Perform all root operations, e.g.,           ****
#  **** "apt-get install" prior to the USER command. ****
#

USER $user_name
ENV HOME /home/$user_name

#
# Install files in the user home directory
#

ADD $labdir/$imagedir/home_tar/home.tar $HOME

# remove after docker fixes problem with empty tars
RUN rm -f $HOME/home.tar
ADD $labdir/$lab.tar.gz $HOME

#
#  The first thing that executes on the container.
#

USER root
RUN echo 'alias check="python3 $HOME/check.py"' >> ~/.bashrc
RUN chmod 777 $HOME/check.py
RUN chmod 777 $HOME/initial.py
RUN chmod 777 $HOME/instructions.py
RUN chmod 777 /etc/rc.local

CMD ["/bin/bash", "-c", "exec /sbin/init --log-target=journal 3>&1"]

